import { useState } from "react";
import { Download, FileText, Filter, Calendar } from "lucide-react";

export default function Reports() {
  const isDemoMode = localStorage.getItem('demoMode') === 'true';
  const isBackendConnected = isDemoMode;

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between md:items-end gap-4">
        <div>
          <h1 className="text-3xl font-heading font-bold text-foreground">Reports</h1>
          <p className="text-slate-400 mt-1">Generate and download security audit and compliance reports</p>
        </div>
      </div>

      {!isBackendConnected ? (
        <div className="glass-card flex flex-col items-center justify-center p-16 text-center min-h-[400px]">
          <div className="w-20 h-20 bg-navy-800 rounded-full flex items-center justify-center mb-6">
            <FileText className="w-10 h-10 text-slate-500" />
          </div>
          <h3 className="text-xl font-medium text-foreground mb-2">No Reports Available</h3>
          <p className="text-slate-400 max-w-md mb-6">
            Reports are generated by the ml_engine based on CVEFixes dataset scans. Please connect the backend to view reports.
          </p>
        </div>
      ) : (
        <div className="glass-card p-6 min-h-[400px]">
          <div className="flex justify-between items-center mb-6 border-b border-border pb-4">
            <h3 className="text-lg font-medium text-foreground">Generated Reports</h3>
            <div className="flex items-center space-x-3">
              <button className="flex items-center space-x-2 px-3 py-1.5 border border-border rounded-md text-sm text-slate-300 hover:bg-white/5 transition-colors">
                <Filter className="w-4 h-4" />
                <span>Filter</span>
              </button>
              <button className="flex items-center space-x-2 px-3 py-1.5 border border-border rounded-md text-sm text-slate-300 hover:bg-white/5 transition-colors">
                <Calendar className="w-4 h-4" />
                <span>Date Range</span>
              </button>
            </div>
          </div>
          <div className="space-y-4">
            {[
              { title: "Weekly Security Audit", repo: "payment-gateway", date: "May 10, 2026", type: "PDF" },
              { title: "OWASP Compliance Report", repo: "auth-service", date: "May 09, 2026", type: "CSV" },
              { title: "Vulnerability Summary", repo: "user-service", date: "May 08, 2026", type: "PDF" },
              { title: "Quarterly Risk Assessment", repo: "All Repositories", date: "May 01, 2026", type: "JSON" }
            ].map((report, idx) => (
              <div key={idx} className="flex justify-between items-center p-4 bg-white/5 rounded-lg border border-border hover:border-primary/50 transition-colors">
                <div className="flex items-center space-x-4">
                  <div className="p-2 bg-primary/10 rounded-lg text-primary">
                    <FileText className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="font-medium text-slate-200">{report.title}</h4>
                    <p className="text-xs text-slate-400 mt-1">{report.repo} • {report.date}</p>
                  </div>
                </div>
                <button className="flex items-center space-x-2 px-3 py-1.5 bg-primary hover:bg-primary-dark text-white rounded-md text-sm font-medium transition-colors">
                  <Download className="w-4 h-4" />
                  <span>Download {report.type}</span>
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}