"""initial_schema

Revision ID: 20fed14e3a38
Revises: 
Create Date: 2026-07-04 23:45:33.803927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fed14e3a38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=36), nullable=False, comment='UUID v4 — CHAR(36) for optimal MySQL B-tree indexing'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='RFC-5321 max email length; used as login identifier'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Display name shown in the UI'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment="bcrypt hash (cost=12) of the user's password. Never store plain-text."),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable flag; False blocks login without deleting data'),
    sa.Column('github_token', sa.Text(), nullable=True, comment='Encrypted GitHub PAT for PR creation; NULL if not connected'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.CHAR(length=36), nullable=False, comment='UUID v4 — CHAR(36) for optimal MySQL B-tree indexing'),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False, comment='FK → users.id; CASCADE DELETE prevents orphaned repos'),
    sa.Column('repo_name', sa.String(length=255), nullable=False, comment="GitHub repository name, e.g. 'owner/repo'"),
    sa.Column('installation_id', sa.Integer(), nullable=False, comment='Numeric GitHub App installation ID for this repository'),
    sa.Column('default_branch', sa.String(length=255), nullable=False, comment='Branch targeted by RepoShield scans'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='Mirrors GitHub repo visibility; affects token requirements'),
    sa.Column('github_repo_url', sa.String(length=2048), nullable=False, comment='Canonical HTTPS URL of the GitHub repository'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional repository description pulled from GitHub API'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_table('vulnerability_jobs',
    sa.Column('id', sa.CHAR(length=36), nullable=False, comment='UUID v4 — CHAR(36) for optimal MySQL B-tree indexing'),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False, comment='FK → users.id (CHAR 36)'),
    sa.Column('repository_id', sa.CHAR(length=36), nullable=True, comment='FK → repositories.id; SET NULL on repo deletion'),
    sa.Column('target_file_path', sa.Text(), nullable=False, comment='Repo-relative path of the file under analysis'),
    sa.Column('business_risk_score', sa.Float(), nullable=False, comment='Normalised risk score [0.0, 1.0] from Model Armor / static scan'),
    sa.Column('patch_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SANDBOXING', 'VERIFIED', 'PATCHED', 'FAILED', 'SKIPPED', name='patch_status_enum'), nullable=False, comment='Current state in the self-healing patch pipeline'),
    sa.Column('model_armor_blocked', sa.Integer(), nullable=False, comment='Commands blocked by Model Armor for this job'),
    sa.Column('self_healing_count', sa.Integer(), nullable=False, comment='Autonomous fix interventions applied during this job'),
    sa.Column('pull_request_url', sa.String(length=2048), nullable=True, comment='GitHub PR URL for the remediation patch; NULL until PR is created'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_jobs_repository_id'), 'vulnerability_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_jobs_user_id'), 'vulnerability_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_jobs_user_id'), table_name='vulnerability_jobs')
    op.drop_index(op.f('ix_vulnerability_jobs_repository_id'), table_name='vulnerability_jobs')
    op.drop_table('vulnerability_jobs')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
